### ISSUE TITLE
removeUserAttribute does not work

### ISSUE THREAD

**Issue by jessicachiuuu** [mParticle/integration-amplitude#6]
https://github.com/mParticle/integration-amplitude/blob/17162c353aa5791f3490bbf3a7dc6ce0479b49fc/Amplitude.js#L101-L110

Ran a quick test on the current code and it unsuccessfully removed the user attribute. Looks like you might need to modify lines 105-107 to the following: 

```
function removeUserAttribute(key) {
                if (isInitialized)  {
                    try {
                        var identify = new amplitude.Identify().unset(key);
                        getInstance().identify(identify);

                        return 'Successfully unset Amplitude user property: ' + key;
                    }
```

Here is our documentation that shows how the `unset` method can be used: https://amplitude.zendesk.com/hc/en-us/articles/115001361248#setting-user-properties

Thanks!

**Comment by rmi22186** [comment]
Hi @jessicachiuuu - thanks for the issue!

This has been fixed [here](https://github.com/mparticle-integrations/mparticle-javascript-integration-amplitude/pull/1/files)

Our new js integrations are stored on the mparticle-integrations org, so please create any further issues/PRs there if you catch anything else.

I'll work to remove these deprecated repos, since the duplication is confusing.
